name: E2E Tests

on:
  pull_request:

jobs:
  Executetest:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start app
        run: |
          npx http-server -p 3000 &
          sleep 5

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Cypress Mochawesome HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/results/
          retention-days: 10